import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Quiz from "@/pages/components/Quiz";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Вибір книги відповідно до&nbsp;
            <code className={styles.code}>побажань користувача</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Курсова робота Кузнецової Аріни
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Quiz/>

        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Зроблено за допомогою Next.js <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Знайти інформацію про Next.js, документація та &nbsp;API.
            </p>
          </a>


        </div>
      </main>
    </>
  )
}
